use crate::iomux::RegisterBlock;
use crate::pad::Pad;

/// Pads structure provides access to all 64 IO pads.
/// Each field represents a mutable reference to a specific Pad instance.
/// Use this structure to configure and control IO pads on the chip.
pub struct Pads {
    pub io0: &'static mut Pad<0>,
    pub io1: &'static mut Pad<1>,
    pub io2: &'static mut Pad<2>,
    pub io3: &'static mut Pad<3>,
    pub io4: &'static mut Pad<4>,
    pub io5: &'static mut Pad<5>,
    pub io6: &'static mut Pad<6>,
    pub io7: &'static mut Pad<7>,
    pub io8: &'static mut Pad<8>,
    pub io9: &'static mut Pad<9>,
    pub io10: &'static mut Pad<10>,
    pub io11: &'static mut Pad<11>,
    pub io12: &'static mut Pad<12>,
    pub io13: &'static mut Pad<13>,
    pub io14: &'static mut Pad<14>,
    pub io15: &'static mut Pad<15>,
    pub io16: &'static mut Pad<16>,
    pub io17: &'static mut Pad<17>,
    pub io18: &'static mut Pad<18>,
    pub io19: &'static mut Pad<19>,
    pub io20: &'static mut Pad<20>,
    pub io21: &'static mut Pad<21>,
    pub io22: &'static mut Pad<22>,
    pub io23: &'static mut Pad<23>,
    pub io24: &'static mut Pad<24>,
    pub io25: &'static mut Pad<25>,
    pub io26: &'static mut Pad<26>,
    pub io27: &'static mut Pad<27>,
    pub io28: &'static mut Pad<28>,
    pub io29: &'static mut Pad<29>,
    pub io30: &'static mut Pad<30>,
    pub io31: &'static mut Pad<31>,
    pub io32: &'static mut Pad<32>,
    pub io33: &'static mut Pad<33>,
    pub io34: &'static mut Pad<34>,
    pub io35: &'static mut Pad<35>,
    pub io36: &'static mut Pad<36>,
    pub io37: &'static mut Pad<37>,
    pub io38: &'static mut Pad<38>,
    pub io39: &'static mut Pad<39>,
    pub io40: &'static mut Pad<40>,
    pub io41: &'static mut Pad<41>,
    pub io42: &'static mut Pad<42>,
    pub io43: &'static mut Pad<43>,
    pub io44: &'static mut Pad<44>,
    pub io45: &'static mut Pad<45>,
    pub io46: &'static mut Pad<46>,
    pub io47: &'static mut Pad<47>,
    pub io48: &'static mut Pad<48>,
    pub io49: &'static mut Pad<49>,
    pub io50: &'static mut Pad<50>,
    pub io51: &'static mut Pad<51>,
    pub io52: &'static mut Pad<52>,
    pub io53: &'static mut Pad<53>,
    pub io54: &'static mut Pad<54>,
    pub io55: &'static mut Pad<55>,
    pub io56: &'static mut Pad<56>,
    pub io57: &'static mut Pad<57>,
    pub io58: &'static mut Pad<58>,
    pub io59: &'static mut Pad<59>,
    pub io60: &'static mut Pad<60>,
    pub io61: &'static mut Pad<61>,
    pub io62: &'static mut Pad<62>,
    pub io63: &'static mut Pad<63>,
}

impl Pads {
    /// Create a new Pads structure from an IOMUX RegisterBlock.
    /// Each pad will correspond to one register in the provided RegisterBlock.
    pub fn new(iomux: &'static mut RegisterBlock) -> Pads {
        Self {
            io0: unsafe { core::mem::transmute(&mut iomux.pads[0]) },
            io1: unsafe { core::mem::transmute(&mut iomux.pads[1]) },
            io2: unsafe { core::mem::transmute(&mut iomux.pads[2]) },
            io3: unsafe { core::mem::transmute(&mut iomux.pads[3]) },
            io4: unsafe { core::mem::transmute(&mut iomux.pads[4]) },
            io5: unsafe { core::mem::transmute(&mut iomux.pads[5]) },
            io6: unsafe { core::mem::transmute(&mut iomux.pads[6]) },
            io7: unsafe { core::mem::transmute(&mut iomux.pads[7]) },
            io8: unsafe { core::mem::transmute(&mut iomux.pads[8]) },
            io9: unsafe { core::mem::transmute(&mut iomux.pads[9]) },

            io10: unsafe { core::mem::transmute(&mut iomux.pads[10]) },
            io11: unsafe { core::mem::transmute(&mut iomux.pads[11]) },
            io12: unsafe { core::mem::transmute(&mut iomux.pads[12]) },
            io13: unsafe { core::mem::transmute(&mut iomux.pads[13]) },
            io14: unsafe { core::mem::transmute(&mut iomux.pads[14]) },
            io15: unsafe { core::mem::transmute(&mut iomux.pads[15]) },
            io16: unsafe { core::mem::transmute(&mut iomux.pads[16]) },
            io17: unsafe { core::mem::transmute(&mut iomux.pads[17]) },
            io18: unsafe { core::mem::transmute(&mut iomux.pads[18]) },
            io19: unsafe { core::mem::transmute(&mut iomux.pads[19]) },

            io20: unsafe { core::mem::transmute(&mut iomux.pads[20]) },
            io21: unsafe { core::mem::transmute(&mut iomux.pads[21]) },
            io22: unsafe { core::mem::transmute(&mut iomux.pads[22]) },
            io23: unsafe { core::mem::transmute(&mut iomux.pads[23]) },
            io24: unsafe { core::mem::transmute(&mut iomux.pads[24]) },
            io25: unsafe { core::mem::transmute(&mut iomux.pads[25]) },
            io26: unsafe { core::mem::transmute(&mut iomux.pads[26]) },
            io27: unsafe { core::mem::transmute(&mut iomux.pads[27]) },
            io28: unsafe { core::mem::transmute(&mut iomux.pads[28]) },
            io29: unsafe { core::mem::transmute(&mut iomux.pads[29]) },

            io30: unsafe { core::mem::transmute(&mut iomux.pads[30]) },
            io31: unsafe { core::mem::transmute(&mut iomux.pads[31]) },
            io32: unsafe { core::mem::transmute(&mut iomux.pads[32]) },
            io33: unsafe { core::mem::transmute(&mut iomux.pads[33]) },
            io34: unsafe { core::mem::transmute(&mut iomux.pads[34]) },
            io35: unsafe { core::mem::transmute(&mut iomux.pads[35]) },
            io36: unsafe { core::mem::transmute(&mut iomux.pads[36]) },
            io37: unsafe { core::mem::transmute(&mut iomux.pads[37]) },
            io38: unsafe { core::mem::transmute(&mut iomux.pads[38]) },
            io39: unsafe { core::mem::transmute(&mut iomux.pads[39]) },

            io40: unsafe { core::mem::transmute(&mut iomux.pads[40]) },
            io41: unsafe { core::mem::transmute(&mut iomux.pads[41]) },
            io42: unsafe { core::mem::transmute(&mut iomux.pads[42]) },
            io43: unsafe { core::mem::transmute(&mut iomux.pads[43]) },
            io44: unsafe { core::mem::transmute(&mut iomux.pads[44]) },
            io45: unsafe { core::mem::transmute(&mut iomux.pads[45]) },
            io46: unsafe { core::mem::transmute(&mut iomux.pads[46]) },
            io47: unsafe { core::mem::transmute(&mut iomux.pads[47]) },
            io48: unsafe { core::mem::transmute(&mut iomux.pads[48]) },
            io49: unsafe { core::mem::transmute(&mut iomux.pads[49]) },

            io50: unsafe { core::mem::transmute(&mut iomux.pads[50]) },
            io51: unsafe { core::mem::transmute(&mut iomux.pads[51]) },
            io52: unsafe { core::mem::transmute(&mut iomux.pads[52]) },
            io53: unsafe { core::mem::transmute(&mut iomux.pads[53]) },
            io54: unsafe { core::mem::transmute(&mut iomux.pads[54]) },
            io55: unsafe { core::mem::transmute(&mut iomux.pads[55]) },
            io56: unsafe { core::mem::transmute(&mut iomux.pads[56]) },
            io57: unsafe { core::mem::transmute(&mut iomux.pads[57]) },
            io58: unsafe { core::mem::transmute(&mut iomux.pads[58]) },
            io59: unsafe { core::mem::transmute(&mut iomux.pads[59]) },

            io60: unsafe { core::mem::transmute(&mut iomux.pads[60]) },
            io61: unsafe { core::mem::transmute(&mut iomux.pads[61]) },
            io62: unsafe { core::mem::transmute(&mut iomux.pads[62]) },
            io63: unsafe { core::mem::transmute(&mut iomux.pads[63]) },
        }
    }
}
